# Generated by Django 4.2.6 on 2023-10-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_relationship_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('serial', models.CharField(max_length=50, verbose_name='Serial')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('created_by', models.CharField(max_length=150, verbose_name='Added by')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_organisation', to='client_relationship_manager.userprofile')),
            ],
        ),
    ]
